[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # タイムアウトを60秒に延長（大きなJSONファイル対応）
  timeout = 60

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
